### ISSUE TITLE
Java: GraphQL: Different behaviour on errors

### ISSUE THREAD

**Issue by knotenpunkt** [amos-project2/metadata-hub#20]
i detected one difference between eav and none eav:
`query
{
  get_metadata(file: "1", attributes:["FileName","blablub"], eav: false)
  {
    name,
    value
  }
}
`
returns this here
`{
  "errors": [
    {
      "message": "Cannot return null for non-nullable type: 'String' within parent 'Attribute' (/get_metadata[1]/value)",
      "path": [
        "get_metadata",
        1,
        "value"
      ],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": {
    "get_metadata": [
      {
        "name": "FileName",
        "value": "hund.jpg"
      },
      null
    ]
  }
}`

and this here

`query
{
  get_metadata(file: "1", attributes:["FileName","blablub"],eav: true)
  {
    name,
    value
  }
}
`

returns this:

`
{
  "data": {
    "get_metadata": [
      {
        "name": "FileName",
        "value": "hund.jpg"
      }
    ]
  }
}`

no error-field in the json

**we want to have the same behaviour here**

**Comment by GregorFendt** [comment]
Fixed in latest Feature_Branch

Requested non-existent attributes always get ignored now :)

**Comment by knotenpunkt** [comment]
you can use the closes keyword in the commit message. That would after the commit is gone to the default branch (master) closes this issue autmatically: https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by knotenpunkt** [comment]
but if you forgot it its no problem you also can link a pull-request manually: https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

it has the same behaviour, it closes after merging to the default branch

**Comment by knotenpunkt** [comment]
i dont know why it is not closed automatically

the closes commits/linked-pull-requests are merged to the master?!
